services:
  db:
    image: ankane/pgvector
    container_name: e-commerce-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


  node:
    image: node:20.19.3
    container_name: node-dev
    working_dir: /app
    volumes:
      - ./frontend:/app

    ports:
      - "3000:3000" 
    stdin_open: true
    tty: true



