version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    restart: unless-stopped
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - USE_CLOUDWATCH=true
      - AWS_REGION=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Mount AWS credentials from EC2 instance
    volumes:
      - ~/.aws:/root/.aws:ro

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    restart: unless-stopped