version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    restart: unless-stopped
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - USE_CLOUDWATCH=True
      - AWS_REGION=eu-north-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3