FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && \
    pip install --no-cache-dir uv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./pyproject.toml ./uv.lock ./
RUN uv sync --no-dev --frozen

COPY ./backend /app/backend
COPY ./startup.sh /app/startup.sh

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
EXPOSE 8000

RUN chmod +x /app/startup.sh

CMD ["/app/startup.sh"]
