"""Add current_location and delivery_address for order tracking

Revision ID: de6611daabbb
Revises: f4a6e1ac7dfc
Create Date: 2025-11-06 19:11:18.474699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de6611daabbb'
down_revision: Union[str, Sequence[str], None] = 'f4a6e1ac7dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('current_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'current_location')
    # ### end Alembic commands ###
